# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Johannes Kiechle
title: M.Sc. Student in Electrical- and Computer Engineering
email: hannes.kiechle@gmail.com
# website: www.hannesk95.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username: hannesk95
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: johannes-kiechle-9b3142178
xing_username: Johannes_Kiechle
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
  # icon: fas fa-globe
  # url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/myself.jpeg
about_content: | # this will include new lines to allow paragraphs
  Servus, my name is Hannes and I'm an open-minded Masters Student at Technical University Munich (TUM) in Electrical and Computer Engineering. My focus is on Automation and Robotics, I'm eager to meet new challenges and I like to think outside the box. My personal interests are particularly related to the fields of Artificial Intelligence (Machine Learning, Deep Learning), Computer Vision, Embedded and Computer Systems, High-Performance-Computing as well as Intelligence on the Edge. A current version of my CV in PDF file format can be found [here.](https://drive.google.com/file/d/1O9_kYG8ZXJeU8kTsx7_3_WTKfWCpVh5a/view?usp=sharing)
    
  <mark>Servus:</mark> The most general way how to welcome somebody in Bavaria.  

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Geometrical Deep Learning on 3D Models - Classification for Additive Manufacturing
        link: https://github.com/hannesk95/Classification-for-Additive-Manufacturing        
        description: | # this will include new lines to allow paragraphs
          The overall goal of this project was about developing an algorithm using deep learning, which is capable of predicting whether a 3D-model is printable or not. In this context, printable refers to the context of additive manufacturing. All work is done in cooperation with the Data Analytics & AI team of (Volkswagen Data:Lab Munich)[https://datalab-munich.de/] carried out in the context of the TUM Data Innovation Lab.

      - layout: top-middle
        title: Unsupervised Anomaly Detection using an Isolation Forest
        link: https://github.com/hannesk95/Unsupervised-Anomaly-Detection       
        description: | # this will include new lines to allow paragraphs
          This work showcases a holistic approach how to perform anomaly detection for rail traffic data of Finland. Therein, a so-called Isolation Forest is trained in order to detect anomal data samples.

      - layout: top-middle
        title: Distributed Dynamic Programming using OpenMPI in C++
        link: https://github.com/hannesk95/Distributed-DP        
        description: | # this will include new lines to allow paragraphs
          In this project, an asynchronous value iteration while heavily using OpenMPI is presented. This is done for the purpose of distributing the entire workload across several physical machines. Different strategies are implemented and benchmarked accordingly.

      - layout: top-middle
        title: Consumer-Producer based Multithreading using Mutex in C++
        link: https://github.com/hannesk95/Consumer-Producer-Model        
        description: | # this will include new lines to allow paragraphs
          This project showcases a producer-consumer model using mutual exclusions (Mutex) in C++ in order to draw the well known Barnsley fern. Therein, the computational workload can distributed among several workers in order to speed up the entire process. The number of workers is selectable and can be adjusted according to the processing hardware at hand.

      - layout: top-middle
        title: Investigating the Impact of COVID-19 on the Climate Change
        link: https://github.com/hannesk95/COVID-19_and_CO2
        # link_text: Project Website
        # additional_links:
          # - title:  sproogen/modern-resume-theme
            # icon: fab fa-github
            # url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
          # This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs          
          In the context of a university lecture called "Applied Machine Intelligence" at Technical University Munich (TUM), chair of data processing, in a group of 8 students, we have been investigating the impact of COVID-19 on the climate change. In order to draw inference on collected data, various machine learning approaches were used.

      - layout: top-middle
        title: Person Image Segmentation using conventional Computer Vision Methods
        link: https://github.com/hannesk95/Person-Image-Segmentation        
        description: | # this will include new lines to allow paragraphs
          This project was carried out as part of the computer vision lecture at the Technical University of Munich (TUM) in the summer semester 2020. The goal of this project was to implement a person image segmentation using conventional computer vision methods.

  - title: Professional Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Siemens Mobility GmbH
        link: www.mobility.siemens.com
        # link_text: boringcompany.com
        sub_title: Working Student 
        caption: April 2021 - Present
      
        description: | # this will include new lines to allow paragraphs
            Responsibility: 
            - Data analytics in rail applications
            - Multivariate time-series anomaly detection using deep autoencoders


      - layout: left
        title: Siemens AG
        link: www.siemens.com
        # link_text: boringcompany.com
        sub_title: Working Student 
        caption: April 2020 - March 2021
      
        description: | # this will include new lines to allow paragraphs
            Responsibilities: 
            - Identify and collect suitable data in the context of communication networks
            - Assessment and implementation of various machine learning and deep learning methods for industrial edge-cloud environments and intelligent manufacturing infrastructure

      - layout: left
        title: Infineon Technologies Asia Pacific Pte. Ltd.
        link: www.infineon.com
        # link_text: boringcompany.com
        sub_title: Internship 
        caption: October 2019 - March 2020
      
        description: | # this will include new lines to allow paragraphs
            Entrusted Project: "Machine Learning based 2.5-Dimensional Face Recognition and Spoof Detection using Depth Data provided by a Time-of-Flight (ToF) Sensor"

            Key Tasks:
            - Development of a sensor interface in order to retrieve data and collect an extensive data set
            - Analysis, synthesis, and training of a suitable neural network architecture which meets real-time requirements
            - Prototypical implementation, testing, and initiation of the face recognition application using a high-performance microcomputer (Nvidia Jetson Nano)


      - layout: left
        title: Infineon Technologies AG
        link: www.infineon.com
        # link_text: boringcompany.com
        sub_title: Bachelor Thesis Student 
        caption: March 2019 - October 2019
      
        description: | # this will include new lines to allow paragraphs
            Scope of Investigation: "Proof of Concept Machine Learning based Control Loop Parameter Optimization for a DC-DC Buck Converter"

            Key tasks: Identify and collect suitable data which subsequently was used to develop, train, and evaluate an eligible deep neural network that is capable of predicting optimal control loop parameters from transient responses.


  - title: Awards # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Best Customer Orientation and Usability Award 
        sub_title: Siemens Summer Camp Digital Twins     
        description: | # this will include new lines to allow paragraphs
            The group challenge which I've been assigned to was: "Connect Real World Scenarios to the Digital Twin of an Autonomous Vehice in Real Time". Personal learning outcomes: Collecting as much information as possible done by a smart infrastructure in real-time and providing this additional knowledge to all possible road users will be for sure one of the key components of future autonomous car deployments. The award in PDF file format can be found [here.](https://drive.google.com/file/d/1RZJxrZYmx3wJrCrdvMbAVl3W-Ur8tmau/view?usp=sharing)

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Technical Universtiy Munich (TUM)
        caption: 04/2020 - Present
        sub_title: M.Sc. Electrical- and Computer Engineering
        description: | # this will include new lines to allow paragraphs
          Outline of subjetcs taken:
          - Applied Machine Intelligence
          - Computer Vision
          - Machine Learning in Robotics
          - Optimal Control and Decision Making
          - High Performace Computing for Machine Intelligence in Python/C++
          - Seminar Machine Learning about Robustness and Distribution Shifts
          - Smart Data Engineering
      
      - layout: left
        title: Technical Universtiy of Denmark (DTU)
        caption: 09/2018 - 01/2019
        sub_title: B.Sc. Computer Science 
                   (Exchange Semester)
        description: | # this will include new lines to allow paragraphs
          Outline of subjetcs taken:
          - Programming in C++
          - Introducion into Machine Learning and Data Mining
          - Introduction to Image Analysis
      
      - layout: left
        title: University of Applied Sciences Munich (MUAS)
        caption: 10/2015 - 03/2020
        sub_title: B.Eng. Electrical Engineering and Information Technology
        description: | # this will include new lines to allow paragraphs
          Outline of subjetcs taken:
          - Programming in C and Java
          - Unix/Linux
          - Microcomputers
          - Embedded Systems
          - Numerical Mathematical Methods
          - Communication Networks          
          - Control Theory
          - Measurement Technology
          - Power Electronics
          - Electrical Machines    

  - title: Programming Experience, OS, API's and Frameworks
    layout: list
    content:
      - layout: left
        title: Programming Languages
        description: |
            - Python
            - C/C++
            - Matlab
            - Java

      - layout: left
        title: Operating System Experience
        description: |
            - Linux
            - Windows            
        
      - layout: left
        title: API's
        description: |
            - OpenMP (Mulitprocessing)
            - OpenMPI (Message Passing Interface)
            - OpenCV (Computer Vision Library)
            - CFFI (C Foreign Function Interface for Python)
      
      - layout: left
        title: Data Science Frameworks
        description: |
            - Keras
            - Tensorflow
            - Scikit-learn
            - Apache MXNet (Gluon)      

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in machine learning and software engineering some of my other interests and hobbies are:
      - Soccer
      - Traveling
      - Cooking
      - [Spending time with friends while having an ice cold beer](https://www.youtube.com/watch?v=dX5QNZtQXX4)


    # Look at this cool image  
    # ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
